"use client"

import { useState } from "react"
import { useParams } from "next/navigation"
import Link from "next/link"
import { Sparkles } from "lucide-react"

const demoContent = {
  instagram: "🧿 قولولي إيه رأيكم في البوست الجديد؟\n\nإحنا شغالين على حاجة جامدة جداً الفترة الجاية وهنعلن عنها قريب.\n\nمستنيين رأيكم 🔥🔥🔥",
  linkedin: "🚀 3 حاجات لازم تعرفهم عن التسويق بالمحتوى في 2026:\n\n1. المحتوى القصير هو المسيطر - ريلز وشورتس\n2. الجمهور عايز محتوى حقيقي مش إعلانات\n3. الذكاء الاصطناعي مش هياخد شغلك - هيخليه أسهل\n\n#تسويق_محتوى #ريادة_أعمال #مصر",
  tiktok: "لو عندك مشروع ومش عارف تبدأ… ابدأ النهارده! 🚀\n\nمش لازم يكون كل حاجة perfect، المهم تبدأ وتتعلم وتتطور. \n\nإحنا معاك في رحلتك ✨",
}

export default function ContentDemo() {
  const params = useParams()
  const locale = params.locale as string
  const isAr = locale === "ar"
  const [activePlatform, setActivePlatform] = useState<"instagram" | "linkedin" | "tiktok">("instagram")

  return (
    <section className="py-20 bg-white">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            {isAr ? "شوف بنفسك جودة المحتوى" : "See Content Quality Yourself"}
          </h2>
          <p className="text-lg text-gray-500 max-w-2xl mx-auto">
            {isAr
              ? "ده مثال حقيقي للمحتوى اللي بيولده ContentAlchemy. جرب بنفسك!"
              : "Here's real content generated by ContentAlchemy. Try it yourself!"}
          </p>
        </div>

        {/* Platform selector */}
        <div className="flex justify-center gap-3 mb-8 flex-wrap">
          {(Object.keys(demoContent) as Array<keyof typeof demoContent>).map((platform) => (
            <button
              key={platform}
              onClick={() => setActivePlatform(platform)}
              className={`px-5 py-2.5 rounded-xl text-sm font-medium transition-all border ${
                activePlatform === platform
                  ? "bg-primary-600 text-white border-primary-600 shadow-md"
                  : "bg-white text-gray-600 border-gray-200 hover:border-primary-200"
              }`}
            >
              {platform === "instagram" ? "Instagram" : platform === "linkedin" ? "LinkedIn" : "TikTok"}
            </button>
          ))}
        </div>

        {/* Content card */}
        <div className="max-w-xl mx-auto bg-gradient-to-br from-gray-50 to-white border border-gray-200 rounded-3xl p-6 shadow-sm">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 bg-primary-100 rounded-full flex items-center justify-center">
              <span className="text-primary-600 font-bold text-sm">C</span>
            </div>
            <div>
              <p className="font-semibold text-gray-900 text-sm">ContentAlchemy</p>
              <p className="text-xs text-gray-400">
                {isAr ? "محتوى تجريبي" : "Demo content"} · {isAr ? "منذ دقائق" : "Just now"}
              </p>
            </div>
          </div>
          <p className="text-gray-800 whitespace-pre-line leading-relaxed mb-4 text-sm">
            {demoContent[activePlatform]}
          </p>
          <div className="flex flex-wrap gap-1.5">
            {([
              ["تسويق", "محتوى", "مصر", "السوشيال_ميديا"],
              ["تسويق_محتوى", "ريادة_أعمال", "مصر", "نصائح"],
              ["مشاريع", "ريادة", "تطوير_ذات", "مصر"],
            ])["instagram linkedin tiktok".split(" ").indexOf(activePlatform)].map((tag, i) => (
              <span key={i} className="text-xs px-2.5 py-1 bg-gray-100 text-gray-600 rounded-full">
                #{tag}
              </span>
            ))}
          </div>
        </div>

        <div className="text-center mt-8">
          <Link
            href={`/${locale}/auth`}
            className="inline-flex items-center gap-2 px-6 py-3 bg-primary-600 text-white rounded-xl hover:bg-primary-700 font-semibold transition-all shadow-md"
          >
            <Sparkles className="w-4 h-4" />
            {isAr ? "جرب دلوقتي مجاناً" : "Try Free Now"}
          </Link>
        </div>
      </div>
    </section>
  )
}
